--- #  Config file for EE lecture note figures


# This section specifies the folder structure
data folder: './data/1-source/'
figures folder: './data/2-figures/'
figure size:
  x: 8.0
  y: 6.0
aspect ratio: 1.0

riskless:
  output folder: 'chapter_riskless/figs/'
